"use client";

/**
 * GanttView — Vue planning complète (toutes interventions + toutes tâches)
 *
 * Colonne gauche sticky (labels), timeline scrollable (barres + marqueurs).
 * Code couleur par intervention via lotLabelColors.
 */

import { useMemo } from "react";
import type { LotSummary } from "@/lib/lotsDb";
import type { LotLabelColorKey } from "@/lib/lotLabelColors";
import { lotLabelColorByKey } from "@/lib/lotLabelColors";

// ─── Types ────────────────────────────────────────────────────────────────────

export type GanttTask = {
  id: string;
  name: string;
  status: string | null;
  start_date: string | null;
  end_date: string | null;
  lot_id: string;
};

type Props = {
  interventions: LotSummary[];
  tasks: GanttTask[];
  lotLabelColors: Record<string, LotLabelColorKey>;
};

// ─── Constants ────────────────────────────────────────────────────────────────

const DAY_W = 24;       // px per day
const ROW_H = 36;       // px per content row
const IV_ROW_H = 40;    // px per intervention header row
const LABEL_W = 270;    // px for fixed label column
const DEFAULT_ACCENT = "#94a3b8";

// ─── Date helpers ─────────────────────────────────────────────────────────────

function fmt(d: Date): string {
  return d.toISOString().slice(0, 10);
}

function addDays(d: Date, n: number): Date {
  const r = new Date(d);
  r.setUTCDate(r.getUTCDate() + n);
  return r;
}

function startOfDay(d: Date): Date {
  return new Date(Date.UTC(d.getFullYear(), d.getMonth(), d.getDate()));
}

function daysBetween(a: Date, b: Date): number {
  return Math.round((b.getTime() - a.getTime()) / 86_400_000);
}

function parseDate(s: string | null): Date | null {
  if (!s) return null;
  const d = new Date(s);
  return isNaN(d.getTime()) ? null : startOfDay(d);
}

function dateToOffset(dateStr: string | null, minDate: Date): number | null {
  const d = parseDate(dateStr);
  if (!d) return null;
  return daysBetween(minDate, d);
}

// ─── Status helpers ──────────────────────────────────────────────────────────

function statusColor(status: string | null): string {
  if (status === "done") return "#10b981";
  if (status === "in_progress") return "#3b82f6";
  return "#94a3b8";
}

function StatusDot({ status }: { status: string | null }) {
  return (
    <span
      className="inline-block w-2 h-2 rounded-full flex-shrink-0"
      style={{ backgroundColor: statusColor(status) }}
      title={status === "done" ? "Terminée" : status === "in_progress" ? "En cours" : "À faire"}
    />
  );
}

// Strip redundant "— InterventionName" suffix from task titles generated by fallback
function cleanTaskName(name: string, interventionName: string): string {
  // Strip "[LotName] " prefix
  let clean = name.replace(/^\[[^\]]+\]\s*/, "");
  // Strip " — InterventionName" suffix (fallback generates "Préparation — LotName")
  const suffix = ` — ${interventionName}`;
  if (clean.endsWith(suffix)) clean = clean.slice(0, -suffix.length);
  // Strip " - InterventionName" variant
  const suffix2 = ` - ${interventionName}`;
  if (clean.endsWith(suffix2)) clean = clean.slice(0, -suffix2.length);
  return clean;
}

// ─── Timeline range ───────────────────────────────────────────────────────────

function computeRange(interventions: LotSummary[], tasks: GanttTask[]) {
  const allDates: Date[] = [];
  const now = startOfDay(new Date());

  for (const iv of interventions) {
    const s = parseDate(iv.startDate ?? iv.tasksStartDate);
    const e = parseDate(iv.endDate ?? iv.tasksEndDate);
    if (s) allDates.push(s);
    if (e) allDates.push(e);
  }
  for (const t of tasks) {
    const d = parseDate(t.end_date ?? t.start_date);
    if (d) allDates.push(d);
  }

  // Always include today
  allDates.push(now);

  const rawMin = new Date(Math.min(...allDates.map((d) => d.getTime())));
  const rawMax = new Date(Math.max(...allDates.map((d) => d.getTime())));

  // Start: 5 days before earliest date (min today - 5 days)
  const minDate = addDays(rawMin, -5);

  // End: at least 90 days from today, or 30 days after last task, whichever is later
  const minEnd = addDays(now, 90);
  const taskEnd = addDays(rawMax, 30);
  const maxDate = new Date(Math.max(minEnd.getTime(), taskEnd.getTime()));

  const totalDays = daysBetween(minDate, maxDate) + 1;
  const days: Date[] = [];
  for (let i = 0; i < totalDays; i++) days.push(addDays(minDate, i));

  return { minDate, maxDate, days, totalDays };
}

// ─── Month groups for header ──────────────────────────────────────────────────

function buildMonthGroups(days: Date[]) {
  type MG = { label: string; count: number };
  const groups: MG[] = [];
  let current = "";
  let count = 0;
  for (const d of days) {
    const label = d.toLocaleDateString("fr-FR", { month: "long", year: "numeric" });
    if (label !== current) {
      if (current) groups.push({ label: current, count });
      current = label;
      count = 0;
    }
    count++;
  }
  if (current) groups.push({ label: current, count });
  return groups;
}

// ─── Weekend + today background layer ────────────────────────────────────────

function TimelineBg({ days, todayOffset }: { days: Date[]; todayOffset: number | null }) {
  return (
    <>
      {days.map((d, i) => {
        const isWeekend = d.getDay() === 0 || d.getDay() === 6;
        const isMonday = d.getDay() === 1;
        if (!isWeekend && !isMonday) return null;
        return (
          <div
            key={i}
            className="absolute inset-y-0 pointer-events-none"
            style={{
              left: i * DAY_W,
              width: isWeekend ? DAY_W : 1,
              backgroundColor: isWeekend ? "rgba(148,163,184,0.07)" : "rgba(148,163,184,0.15)",
            }}
          />
        );
      })}
      {todayOffset !== null && (
        <div
          className="absolute inset-y-0 w-0.5 pointer-events-none"
          style={{ left: todayOffset * DAY_W + DAY_W / 2, backgroundColor: "rgba(99,102,241,0.5)" }}
        />
      )}
    </>
  );
}

// ─── Main Component ───────────────────────────────────────────────────────────

export default function GanttView({ interventions, tasks, lotLabelColors }: Props) {
  const today = fmt(startOfDay(new Date()));

  // Group tasks by lot_id
  const tasksByLot = useMemo(() => {
    const map: Record<string, GanttTask[]> = {};
    for (const t of tasks) {
      if (!t.lot_id) continue;
      if (!map[t.lot_id]) map[t.lot_id] = [];
      map[t.lot_id].push(t);
    }
    return map;
  }, [tasks]);

  const { minDate, days, totalDays } = useMemo(
    () => computeRange(interventions, tasks),
    [interventions, tasks]
  );

  const totalW = totalDays * DAY_W;
  const todayOffset = dateToOffset(today, minDate);
  const monthGroups = useMemo(() => buildMonthGroups(days), [days]);

  if (interventions.length === 0) {
    return (
      <div className="rounded-xl border border-gray-200 bg-white p-10 text-center text-sm text-gray-500">
        Aucune intervention dans ce projet.
      </div>
    );
  }

  return (
    <div className="rounded-xl border border-gray-200 bg-white overflow-hidden shadow-sm">

      {/* ── Legend ── */}
      <div className="flex flex-wrap gap-4 px-4 py-2.5 border-b border-gray-100 bg-gray-50/70">
        {interventions.map((iv) => {
          const key = lotLabelColors[iv.id];
          const info = key ? lotLabelColorByKey[key] : null;
          const accent = info?.accentHex ?? DEFAULT_ACCENT;
          return (
            <div key={iv.id} className="flex items-center gap-1.5">
              <span className="w-3 h-3 rounded flex-shrink-0" style={{ backgroundColor: accent }} />
              <span className="text-xs text-gray-600 font-medium">{iv.name}</span>
            </div>
          );
        })}
        <div className="flex items-center gap-1.5 ml-auto">
          <span className="w-0.5 h-3 rounded bg-indigo-400 flex-shrink-0" />
          <span className="text-xs text-gray-500">Aujourd'hui</span>
        </div>
        <div className="flex items-center gap-3 text-[10px] text-gray-400 border-l border-gray-200 pl-3">
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-emerald-500" />Terminée</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-blue-500" />En cours</span>
          <span className="flex items-center gap-1"><span className="w-2 h-2 rounded-full bg-gray-400" />À faire</span>
        </div>
      </div>

      {/* ── Gantt grid ── */}
      <div className="overflow-x-auto">
        <div style={{ minWidth: LABEL_W + totalW }}>

          {/* Month header */}
          <div className="flex sticky top-0 z-20 border-b border-gray-200" style={{ height: 26 }}>
            <div
              className="flex-shrink-0 flex items-center px-3 bg-white border-r border-gray-200"
              style={{ width: LABEL_W, position: "sticky", left: 0, zIndex: 30 }}
            >
              <span className="text-[10px] font-bold text-gray-400 uppercase tracking-widest">Tâches</span>
            </div>
            <div className="flex bg-gray-50" style={{ width: totalW }}>
              {monthGroups.map((mg, i) => (
                <div
                  key={i}
                  className="flex items-center px-2 border-r border-gray-200 overflow-hidden"
                  style={{ width: mg.count * DAY_W, flexShrink: 0 }}
                >
                  <span className="text-[10px] font-bold text-gray-500 uppercase tracking-wide whitespace-nowrap capitalize">
                    {mg.label}
                  </span>
                </div>
              ))}
            </div>
          </div>

          {/* Day header */}
          <div className="flex sticky top-[26px] z-20 border-b border-gray-200" style={{ height: 22 }}>
            <div
              className="flex-shrink-0 border-r border-gray-200 bg-white"
              style={{ width: LABEL_W, position: "sticky", left: 0, zIndex: 30 }}
            />
            <div className="flex relative" style={{ width: totalW }}>
              {days.map((d, i) => {
                const isWeekend = d.getDay() === 0 || d.getDay() === 6;
                const isToday = fmt(d) === today;
                // Only show number on odd days to avoid crowding
                const showNum = d.getDate() % 2 === 1 || isToday || d.getDate() === 1;
                return (
                  <div
                    key={i}
                    className="flex items-center justify-center flex-shrink-0 text-[9px] font-semibold border-r border-gray-100"
                    style={{
                      width: DAY_W,
                      backgroundColor: isToday ? "rgba(99,102,241,0.12)" : isWeekend ? "rgba(148,163,184,0.08)" : "#f9fafb",
                      color: isToday ? "#4f46e5" : isWeekend ? "#94a3b8" : "#9ca3af",
                    }}
                  >
                    {showNum ? d.getDate() : ""}
                  </div>
                );
              })}
            </div>
          </div>

          {/* Intervention rows */}
          {interventions.map((iv) => {
            const colorKey = lotLabelColors[iv.id] ?? null;
            const colorInfo = colorKey ? lotLabelColorByKey[colorKey] : null;
            const accent = colorInfo?.accentHex ?? DEFAULT_ACCENT;
            const ivTasks = tasksByLot[iv.id] ?? [];

            // Intervention bar span
            const ivStartOff = dateToOffset(iv.startDate ?? iv.tasksStartDate, minDate);
            const ivEndOff = dateToOffset(iv.endDate ?? iv.tasksEndDate, minDate);
            const barLeft = ivStartOff !== null ? ivStartOff * DAY_W : null;
            const barRight = ivEndOff !== null ? (ivEndOff + 1) * DAY_W : null;
            const barWidth = barLeft !== null && barRight !== null ? Math.max(DAY_W * 2, barRight - barLeft) : null;

            return (
              <div key={iv.id} className="group">

                {/* ── Intervention header row ── */}
                <div
                  className="flex border-b border-gray-200"
                  style={{ height: IV_ROW_H, backgroundColor: `${accent}0a` }}
                >
                  {/* Sticky label — fully opaque white so timeline bars don't bleed through */}
                  <div
                    className="flex-shrink-0 flex items-center gap-2 px-3 border-r border-gray-200"
                    style={{
                      width: LABEL_W,
                      position: "sticky",
                      left: 0,
                      zIndex: 12,
                      borderLeft: `4px solid ${accent}`,
                      backgroundColor: "white",
                    }}
                  >
                    <span className="truncate text-[13px] font-semibold text-gray-800 flex-1 leading-tight">
                      {iv.name}
                    </span>
                    <span className="text-[11px] text-gray-400 flex-shrink-0 font-medium tabular-nums">
                      {iv.tasksDone}/{iv.tasksTotal}
                    </span>
                  </div>

                  {/* Timeline */}
                  <div className="relative overflow-hidden" style={{ width: totalW }}>
                    <TimelineBg days={days} todayOffset={todayOffset} />
                    {/* Full span bar (light) */}
                    {barLeft !== null && barWidth !== null && (
                      <div
                        className="absolute top-1/2 -translate-y-1/2 rounded-md"
                        style={{ left: barLeft, width: barWidth, height: 18, backgroundColor: accent, opacity: 0.18 }}
                      />
                    )}
                    {/* Progress fill */}
                    {barLeft !== null && barWidth !== null && iv.progressPercentage > 0 && (
                      <div
                        className="absolute top-1/2 -translate-y-1/2 rounded-l-md"
                        style={{
                          left: barLeft,
                          width: Math.max(6, barWidth * iv.progressPercentage / 100),
                          height: 18,
                          backgroundColor: accent,
                          opacity: 0.55,
                        }}
                      />
                    )}
                    {/* Progress % label */}
                    {barLeft !== null && barWidth !== null && (
                      <div
                        className="absolute top-1/2 -translate-y-1/2 flex items-center px-1.5"
                        style={{ left: barLeft, width: barWidth, height: 18, pointerEvents: "none" }}
                      >
                        {iv.progressPercentage > 0 && (
                          <span className="text-[9px] font-bold ml-auto" style={{ color: accent }}>
                            {iv.progressPercentage}%
                          </span>
                        )}
                      </div>
                    )}
                  </div>
                </div>

                {/* ── Task rows ── */}
                {ivTasks.length === 0 ? (
                  <div className="flex border-b border-gray-100" style={{ height: ROW_H }}>
                    <div
                      className="flex-shrink-0 flex items-center px-4 border-r border-gray-100"
                      style={{ width: LABEL_W, position: "sticky", left: 0, zIndex: 11, backgroundColor: "white" }}
                    >
                      <span className="text-xs text-gray-400 italic">Aucune tâche planifiée</span>
                    </div>
                    <div className="relative overflow-hidden" style={{ width: totalW }}>
                      <TimelineBg days={days} todayOffset={todayOffset} />
                    </div>
                  </div>
                ) : (
                  ivTasks.map((task) => {
                    const taskDate = task.end_date ?? task.start_date;
                    const tOffset = dateToOffset(taskDate, minDate);
                    const tColor = statusColor(task.status);
                    const displayName = cleanTaskName(task.name, iv.name);

                    return (
                      <div key={task.id} className="flex border-b border-gray-100 hover:bg-gray-50/50 transition-colors" style={{ height: ROW_H }}>
                        {/* Sticky label — explicit opaque white so timeline never bleeds through */}
                        <div
                          className="flex-shrink-0 flex items-center gap-2 px-3 border-r border-gray-100"
                          style={{ width: LABEL_W, position: "sticky", left: 0, zIndex: 11, backgroundColor: "white" }}
                        >
                          {/* Vertical connector */}
                          <div className="w-px self-stretch flex-shrink-0 ml-3" style={{ backgroundColor: accent, opacity: 0.3 }} />
                          <StatusDot status={task.status} />
                          <span className="truncate text-xs text-gray-700 flex-1 leading-tight">{displayName}</span>
                          {!taskDate && (
                            <span className="text-[9px] bg-gray-100 text-gray-400 px-1.5 py-0.5 rounded-full flex-shrink-0">
                              non planifié
                            </span>
                          )}
                        </div>

                        {/* Timeline cell */}
                        <div className="relative overflow-hidden" style={{ width: totalW }}>
                          <TimelineBg days={days} todayOffset={todayOffset} />
                          {/* Task bar / milestone */}
                          {tOffset !== null && (
                            <div
                              className="absolute top-1/2 -translate-y-1/2 rounded-sm"
                              title={`${displayName}${taskDate ? ` — ${taskDate}` : ""}`}
                              style={{
                                left: tOffset * DAY_W + 2,
                                width: DAY_W * 1.5,
                                height: 16,
                                backgroundColor: `${tColor}1a`,
                                border: `1.5px solid ${tColor}`,
                              }}
                            />
                          )}
                        </div>
                      </div>
                    );
                  })
                )}
              </div>
            );
          })}

          {/* Bottom padding */}
          <div style={{ height: 6 }} />
        </div>
      </div>
    </div>
  );
}
